
name: Run Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on PR to the master/main branch. 
  push:
  # It is advised to work on a feature branch and not the master/main branch.
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains one job: It opens the project file and runs the test vis from Tests folder.
  open-labview:

    runs-on: self-hosted

    steps:
      # Checkout the repository to the runner
      # - name: Open LabVIEW
      #   run: |
      #       "C:\Program Files\National Instruments\LabVIEW 2020\LabVIEW.exe"
      #   shell: cmd


      - name: Close LabVIEW
        run: |
            taskkill /im LabVIEW.exe
        shell: cmd


      



